#!/bin/sh
# Regenerate src/sc_table.h from tools/syscalls.txt.
#
#   sh tools/gen_syscalls.sh        (from the package root)
#
# A preprocessor X-macro cannot emit #ifdef, so the guarded entries are
# generated here and the output is committed; the package build has no
# generator step (design.md section 5.2).
set -eu

in=tools/syscalls.txt
out=src/sc_table.h

{
    echo "/* Generated by tools/gen_syscalls.sh from tools/syscalls.txt. Do not edit."
    echo " * Each entry exists only when <sys/syscall.h> defines SYS_<name> for the"
    echo " * build architecture, so names and numbers are always the target's own. */"
    echo "static const struct lk_sc_entry lk_sc_table[] = {"
    grep -v '^[[:space:]]*#' "$in" | grep -v '^[[:space:]]*$' | while read -r name; do
        printf '#ifdef SYS_%s\n    { "%s", SYS_%s },\n#endif\n' "$name" "$name" "$name"
    done
    echo "    { NULL, -1 } /* sentinel: keeps the initializer non-empty */"
    echo "};"
} > "$out"

echo "wrote $out ($(grep -c '^#ifdef' "$out") names)"
