/* Generated by tools/gen_syscalls.sh from tools/syscalls.txt. Do not edit.
 * Each entry exists only when <sys/syscall.h> defines SYS_<name> for the
 * build architecture, so names and numbers are always the target's own. */
static const struct lk_sc_entry lk_sc_table[] = {
#ifdef SYS_read
    { "read", SYS_read },
#endif
#ifdef SYS_write
    { "write", SYS_write },
#endif
#ifdef SYS_open
    { "open", SYS_open },
#endif
#ifdef SYS_openat
    { "openat", SYS_openat },
#endif
#ifdef SYS_openat2
    { "openat2", SYS_openat2 },
#endif
#ifdef SYS_close
    { "close", SYS_close },
#endif
#ifdef SYS_close_range
    { "close_range", SYS_close_range },
#endif
#ifdef SYS_creat
    { "creat", SYS_creat },
#endif
#ifdef SYS_pread64
    { "pread64", SYS_pread64 },
#endif
#ifdef SYS_pwrite64
    { "pwrite64", SYS_pwrite64 },
#endif
#ifdef SYS_readv
    { "readv", SYS_readv },
#endif
#ifdef SYS_writev
    { "writev", SYS_writev },
#endif
#ifdef SYS_lseek
    { "lseek", SYS_lseek },
#endif
#ifdef SYS_dup
    { "dup", SYS_dup },
#endif
#ifdef SYS_dup2
    { "dup2", SYS_dup2 },
#endif
#ifdef SYS_dup3
    { "dup3", SYS_dup3 },
#endif
#ifdef SYS_pipe
    { "pipe", SYS_pipe },
#endif
#ifdef SYS_pipe2
    { "pipe2", SYS_pipe2 },
#endif
#ifdef SYS_fcntl
    { "fcntl", SYS_fcntl },
#endif
#ifdef SYS_flock
    { "flock", SYS_flock },
#endif
#ifdef SYS_fsync
    { "fsync", SYS_fsync },
#endif
#ifdef SYS_fdatasync
    { "fdatasync", SYS_fdatasync },
#endif
#ifdef SYS_truncate
    { "truncate", SYS_truncate },
#endif
#ifdef SYS_ftruncate
    { "ftruncate", SYS_ftruncate },
#endif
#ifdef SYS_ioctl
    { "ioctl", SYS_ioctl },
#endif
#ifdef SYS_stat
    { "stat", SYS_stat },
#endif
#ifdef SYS_fstat
    { "fstat", SYS_fstat },
#endif
#ifdef SYS_lstat
    { "lstat", SYS_lstat },
#endif
#ifdef SYS_newfstatat
    { "newfstatat", SYS_newfstatat },
#endif
#ifdef SYS_statx
    { "statx", SYS_statx },
#endif
#ifdef SYS_statfs
    { "statfs", SYS_statfs },
#endif
#ifdef SYS_fstatfs
    { "fstatfs", SYS_fstatfs },
#endif
#ifdef SYS_access
    { "access", SYS_access },
#endif
#ifdef SYS_faccessat
    { "faccessat", SYS_faccessat },
#endif
#ifdef SYS_faccessat2
    { "faccessat2", SYS_faccessat2 },
#endif
#ifdef SYS_getdents
    { "getdents", SYS_getdents },
#endif
#ifdef SYS_getdents64
    { "getdents64", SYS_getdents64 },
#endif
#ifdef SYS_getcwd
    { "getcwd", SYS_getcwd },
#endif
#ifdef SYS_chdir
    { "chdir", SYS_chdir },
#endif
#ifdef SYS_fchdir
    { "fchdir", SYS_fchdir },
#endif
#ifdef SYS_rename
    { "rename", SYS_rename },
#endif
#ifdef SYS_renameat
    { "renameat", SYS_renameat },
#endif
#ifdef SYS_renameat2
    { "renameat2", SYS_renameat2 },
#endif
#ifdef SYS_mkdir
    { "mkdir", SYS_mkdir },
#endif
#ifdef SYS_mkdirat
    { "mkdirat", SYS_mkdirat },
#endif
#ifdef SYS_rmdir
    { "rmdir", SYS_rmdir },
#endif
#ifdef SYS_link
    { "link", SYS_link },
#endif
#ifdef SYS_linkat
    { "linkat", SYS_linkat },
#endif
#ifdef SYS_unlink
    { "unlink", SYS_unlink },
#endif
#ifdef SYS_unlinkat
    { "unlinkat", SYS_unlinkat },
#endif
#ifdef SYS_symlink
    { "symlink", SYS_symlink },
#endif
#ifdef SYS_symlinkat
    { "symlinkat", SYS_symlinkat },
#endif
#ifdef SYS_readlink
    { "readlink", SYS_readlink },
#endif
#ifdef SYS_readlinkat
    { "readlinkat", SYS_readlinkat },
#endif
#ifdef SYS_chmod
    { "chmod", SYS_chmod },
#endif
#ifdef SYS_fchmod
    { "fchmod", SYS_fchmod },
#endif
#ifdef SYS_fchmodat
    { "fchmodat", SYS_fchmodat },
#endif
#ifdef SYS_chown
    { "chown", SYS_chown },
#endif
#ifdef SYS_fchown
    { "fchown", SYS_fchown },
#endif
#ifdef SYS_fchownat
    { "fchownat", SYS_fchownat },
#endif
#ifdef SYS_lchown
    { "lchown", SYS_lchown },
#endif
#ifdef SYS_umask
    { "umask", SYS_umask },
#endif
#ifdef SYS_mknod
    { "mknod", SYS_mknod },
#endif
#ifdef SYS_mknodat
    { "mknodat", SYS_mknodat },
#endif
#ifdef SYS_sendfile
    { "sendfile", SYS_sendfile },
#endif
#ifdef SYS_splice
    { "splice", SYS_splice },
#endif
#ifdef SYS_tee
    { "tee", SYS_tee },
#endif
#ifdef SYS_copy_file_range
    { "copy_file_range", SYS_copy_file_range },
#endif
#ifdef SYS_memfd_create
    { "memfd_create", SYS_memfd_create },
#endif
#ifdef SYS_memfd_secret
    { "memfd_secret", SYS_memfd_secret },
#endif
#ifdef SYS_inotify_init
    { "inotify_init", SYS_inotify_init },
#endif
#ifdef SYS_inotify_init1
    { "inotify_init1", SYS_inotify_init1 },
#endif
#ifdef SYS_fanotify_init
    { "fanotify_init", SYS_fanotify_init },
#endif
#ifdef SYS_fanotify_mark
    { "fanotify_mark", SYS_fanotify_mark },
#endif
#ifdef SYS_name_to_handle_at
    { "name_to_handle_at", SYS_name_to_handle_at },
#endif
#ifdef SYS_open_by_handle_at
    { "open_by_handle_at", SYS_open_by_handle_at },
#endif
#ifdef SYS_mmap
    { "mmap", SYS_mmap },
#endif
#ifdef SYS_munmap
    { "munmap", SYS_munmap },
#endif
#ifdef SYS_mprotect
    { "mprotect", SYS_mprotect },
#endif
#ifdef SYS_mremap
    { "mremap", SYS_mremap },
#endif
#ifdef SYS_msync
    { "msync", SYS_msync },
#endif
#ifdef SYS_mincore
    { "mincore", SYS_mincore },
#endif
#ifdef SYS_madvise
    { "madvise", SYS_madvise },
#endif
#ifdef SYS_brk
    { "brk", SYS_brk },
#endif
#ifdef SYS_mlock
    { "mlock", SYS_mlock },
#endif
#ifdef SYS_munlock
    { "munlock", SYS_munlock },
#endif
#ifdef SYS_mlockall
    { "mlockall", SYS_mlockall },
#endif
#ifdef SYS_munlockall
    { "munlockall", SYS_munlockall },
#endif
#ifdef SYS_mbind
    { "mbind", SYS_mbind },
#endif
#ifdef SYS_set_mempolicy
    { "set_mempolicy", SYS_set_mempolicy },
#endif
#ifdef SYS_get_mempolicy
    { "get_mempolicy", SYS_get_mempolicy },
#endif
#ifdef SYS_migrate_pages
    { "migrate_pages", SYS_migrate_pages },
#endif
#ifdef SYS_move_pages
    { "move_pages", SYS_move_pages },
#endif
#ifdef SYS_userfaultfd
    { "userfaultfd", SYS_userfaultfd },
#endif
#ifdef SYS_fork
    { "fork", SYS_fork },
#endif
#ifdef SYS_vfork
    { "vfork", SYS_vfork },
#endif
#ifdef SYS_clone
    { "clone", SYS_clone },
#endif
#ifdef SYS_clone3
    { "clone3", SYS_clone3 },
#endif
#ifdef SYS_execve
    { "execve", SYS_execve },
#endif
#ifdef SYS_execveat
    { "execveat", SYS_execveat },
#endif
#ifdef SYS_exit
    { "exit", SYS_exit },
#endif
#ifdef SYS_exit_group
    { "exit_group", SYS_exit_group },
#endif
#ifdef SYS_wait4
    { "wait4", SYS_wait4 },
#endif
#ifdef SYS_waitid
    { "waitid", SYS_waitid },
#endif
#ifdef SYS_kill
    { "kill", SYS_kill },
#endif
#ifdef SYS_tkill
    { "tkill", SYS_tkill },
#endif
#ifdef SYS_tgkill
    { "tgkill", SYS_tgkill },
#endif
#ifdef SYS_pidfd_open
    { "pidfd_open", SYS_pidfd_open },
#endif
#ifdef SYS_pidfd_getfd
    { "pidfd_getfd", SYS_pidfd_getfd },
#endif
#ifdef SYS_pidfd_send_signal
    { "pidfd_send_signal", SYS_pidfd_send_signal },
#endif
#ifdef SYS_getpid
    { "getpid", SYS_getpid },
#endif
#ifdef SYS_getppid
    { "getppid", SYS_getppid },
#endif
#ifdef SYS_gettid
    { "gettid", SYS_gettid },
#endif
#ifdef SYS_getpgid
    { "getpgid", SYS_getpgid },
#endif
#ifdef SYS_setpgid
    { "setpgid", SYS_setpgid },
#endif
#ifdef SYS_getpgrp
    { "getpgrp", SYS_getpgrp },
#endif
#ifdef SYS_getsid
    { "getsid", SYS_getsid },
#endif
#ifdef SYS_setsid
    { "setsid", SYS_setsid },
#endif
#ifdef SYS_getpriority
    { "getpriority", SYS_getpriority },
#endif
#ifdef SYS_setpriority
    { "setpriority", SYS_setpriority },
#endif
#ifdef SYS_sched_setscheduler
    { "sched_setscheduler", SYS_sched_setscheduler },
#endif
#ifdef SYS_sched_setaffinity
    { "sched_setaffinity", SYS_sched_setaffinity },
#endif
#ifdef SYS_prctl
    { "prctl", SYS_prctl },
#endif
#ifdef SYS_arch_prctl
    { "arch_prctl", SYS_arch_prctl },
#endif
#ifdef SYS_personality
    { "personality", SYS_personality },
#endif
#ifdef SYS_ptrace
    { "ptrace", SYS_ptrace },
#endif
#ifdef SYS_process_vm_readv
    { "process_vm_readv", SYS_process_vm_readv },
#endif
#ifdef SYS_process_vm_writev
    { "process_vm_writev", SYS_process_vm_writev },
#endif
#ifdef SYS_kcmp
    { "kcmp", SYS_kcmp },
#endif
#ifdef SYS_seccomp
    { "seccomp", SYS_seccomp },
#endif
#ifdef SYS_getuid
    { "getuid", SYS_getuid },
#endif
#ifdef SYS_geteuid
    { "geteuid", SYS_geteuid },
#endif
#ifdef SYS_getgid
    { "getgid", SYS_getgid },
#endif
#ifdef SYS_getegid
    { "getegid", SYS_getegid },
#endif
#ifdef SYS_setuid
    { "setuid", SYS_setuid },
#endif
#ifdef SYS_setgid
    { "setgid", SYS_setgid },
#endif
#ifdef SYS_setreuid
    { "setreuid", SYS_setreuid },
#endif
#ifdef SYS_setregid
    { "setregid", SYS_setregid },
#endif
#ifdef SYS_setresuid
    { "setresuid", SYS_setresuid },
#endif
#ifdef SYS_setresgid
    { "setresgid", SYS_setresgid },
#endif
#ifdef SYS_getresuid
    { "getresuid", SYS_getresuid },
#endif
#ifdef SYS_getresgid
    { "getresgid", SYS_getresgid },
#endif
#ifdef SYS_setfsuid
    { "setfsuid", SYS_setfsuid },
#endif
#ifdef SYS_setfsgid
    { "setfsgid", SYS_setfsgid },
#endif
#ifdef SYS_getgroups
    { "getgroups", SYS_getgroups },
#endif
#ifdef SYS_setgroups
    { "setgroups", SYS_setgroups },
#endif
#ifdef SYS_capget
    { "capget", SYS_capget },
#endif
#ifdef SYS_capset
    { "capset", SYS_capset },
#endif
#ifdef SYS_unshare
    { "unshare", SYS_unshare },
#endif
#ifdef SYS_setns
    { "setns", SYS_setns },
#endif
#ifdef SYS_mount
    { "mount", SYS_mount },
#endif
#ifdef SYS_umount2
    { "umount2", SYS_umount2 },
#endif
#ifdef SYS_pivot_root
    { "pivot_root", SYS_pivot_root },
#endif
#ifdef SYS_chroot
    { "chroot", SYS_chroot },
#endif
#ifdef SYS_mount_setattr
    { "mount_setattr", SYS_mount_setattr },
#endif
#ifdef SYS_move_mount
    { "move_mount", SYS_move_mount },
#endif
#ifdef SYS_open_tree
    { "open_tree", SYS_open_tree },
#endif
#ifdef SYS_fsopen
    { "fsopen", SYS_fsopen },
#endif
#ifdef SYS_fsmount
    { "fsmount", SYS_fsmount },
#endif
#ifdef SYS_fsconfig
    { "fsconfig", SYS_fsconfig },
#endif
#ifdef SYS_fspick
    { "fspick", SYS_fspick },
#endif
#ifdef SYS_sethostname
    { "sethostname", SYS_sethostname },
#endif
#ifdef SYS_setdomainname
    { "setdomainname", SYS_setdomainname },
#endif
#ifdef SYS_reboot
    { "reboot", SYS_reboot },
#endif
#ifdef SYS_kexec_load
    { "kexec_load", SYS_kexec_load },
#endif
#ifdef SYS_kexec_file_load
    { "kexec_file_load", SYS_kexec_file_load },
#endif
#ifdef SYS_init_module
    { "init_module", SYS_init_module },
#endif
#ifdef SYS_finit_module
    { "finit_module", SYS_finit_module },
#endif
#ifdef SYS_delete_module
    { "delete_module", SYS_delete_module },
#endif
#ifdef SYS_swapon
    { "swapon", SYS_swapon },
#endif
#ifdef SYS_swapoff
    { "swapoff", SYS_swapoff },
#endif
#ifdef SYS_acct
    { "acct", SYS_acct },
#endif
#ifdef SYS_quotactl
    { "quotactl", SYS_quotactl },
#endif
#ifdef SYS_syslog
    { "syslog", SYS_syslog },
#endif
#ifdef SYS_vhangup
    { "vhangup", SYS_vhangup },
#endif
#ifdef SYS_ioperm
    { "ioperm", SYS_ioperm },
#endif
#ifdef SYS_iopl
    { "iopl", SYS_iopl },
#endif
#ifdef SYS_settimeofday
    { "settimeofday", SYS_settimeofday },
#endif
#ifdef SYS_clock_settime
    { "clock_settime", SYS_clock_settime },
#endif
#ifdef SYS_adjtimex
    { "adjtimex", SYS_adjtimex },
#endif
#ifdef SYS_clock_adjtime
    { "clock_adjtime", SYS_clock_adjtime },
#endif
#ifdef SYS_bpf
    { "bpf", SYS_bpf },
#endif
#ifdef SYS_perf_event_open
    { "perf_event_open", SYS_perf_event_open },
#endif
#ifdef SYS_lookup_dcookie
    { "lookup_dcookie", SYS_lookup_dcookie },
#endif
#ifdef SYS_keyctl
    { "keyctl", SYS_keyctl },
#endif
#ifdef SYS_add_key
    { "add_key", SYS_add_key },
#endif
#ifdef SYS_request_key
    { "request_key", SYS_request_key },
#endif
#ifdef SYS_io_uring_setup
    { "io_uring_setup", SYS_io_uring_setup },
#endif
#ifdef SYS_io_uring_enter
    { "io_uring_enter", SYS_io_uring_enter },
#endif
#ifdef SYS_io_uring_register
    { "io_uring_register", SYS_io_uring_register },
#endif
#ifdef SYS_landlock_create_ruleset
    { "landlock_create_ruleset", SYS_landlock_create_ruleset },
#endif
#ifdef SYS_landlock_add_rule
    { "landlock_add_rule", SYS_landlock_add_rule },
#endif
#ifdef SYS_landlock_restrict_self
    { "landlock_restrict_self", SYS_landlock_restrict_self },
#endif
#ifdef SYS_socket
    { "socket", SYS_socket },
#endif
#ifdef SYS_socketpair
    { "socketpair", SYS_socketpair },
#endif
#ifdef SYS_connect
    { "connect", SYS_connect },
#endif
#ifdef SYS_bind
    { "bind", SYS_bind },
#endif
#ifdef SYS_listen
    { "listen", SYS_listen },
#endif
#ifdef SYS_accept
    { "accept", SYS_accept },
#endif
#ifdef SYS_accept4
    { "accept4", SYS_accept4 },
#endif
#ifdef SYS_sendto
    { "sendto", SYS_sendto },
#endif
#ifdef SYS_recvfrom
    { "recvfrom", SYS_recvfrom },
#endif
#ifdef SYS_sendmsg
    { "sendmsg", SYS_sendmsg },
#endif
#ifdef SYS_recvmsg
    { "recvmsg", SYS_recvmsg },
#endif
#ifdef SYS_sendmmsg
    { "sendmmsg", SYS_sendmmsg },
#endif
#ifdef SYS_recvmmsg
    { "recvmmsg", SYS_recvmmsg },
#endif
#ifdef SYS_shutdown
    { "shutdown", SYS_shutdown },
#endif
#ifdef SYS_getsockname
    { "getsockname", SYS_getsockname },
#endif
#ifdef SYS_getpeername
    { "getpeername", SYS_getpeername },
#endif
#ifdef SYS_setsockopt
    { "setsockopt", SYS_setsockopt },
#endif
#ifdef SYS_getsockopt
    { "getsockopt", SYS_getsockopt },
#endif
#ifdef SYS_nanosleep
    { "nanosleep", SYS_nanosleep },
#endif
#ifdef SYS_clock_nanosleep
    { "clock_nanosleep", SYS_clock_nanosleep },
#endif
#ifdef SYS_clock_gettime
    { "clock_gettime", SYS_clock_gettime },
#endif
#ifdef SYS_gettimeofday
    { "gettimeofday", SYS_gettimeofday },
#endif
#ifdef SYS_uname
    { "uname", SYS_uname },
#endif
#ifdef SYS_sysinfo
    { "sysinfo", SYS_sysinfo },
#endif
#ifdef SYS_getrandom
    { "getrandom", SYS_getrandom },
#endif
#ifdef SYS_getrlimit
    { "getrlimit", SYS_getrlimit },
#endif
#ifdef SYS_setrlimit
    { "setrlimit", SYS_setrlimit },
#endif
#ifdef SYS_prlimit64
    { "prlimit64", SYS_prlimit64 },
#endif
#ifdef SYS_getrusage
    { "getrusage", SYS_getrusage },
#endif
#ifdef SYS_futex
    { "futex", SYS_futex },
#endif
#ifdef SYS_poll
    { "poll", SYS_poll },
#endif
#ifdef SYS_ppoll
    { "ppoll", SYS_ppoll },
#endif
#ifdef SYS_select
    { "select", SYS_select },
#endif
#ifdef SYS_pselect6
    { "pselect6", SYS_pselect6 },
#endif
#ifdef SYS_epoll_create
    { "epoll_create", SYS_epoll_create },
#endif
#ifdef SYS_epoll_create1
    { "epoll_create1", SYS_epoll_create1 },
#endif
#ifdef SYS_epoll_ctl
    { "epoll_ctl", SYS_epoll_ctl },
#endif
#ifdef SYS_epoll_wait
    { "epoll_wait", SYS_epoll_wait },
#endif
#ifdef SYS_epoll_pwait
    { "epoll_pwait", SYS_epoll_pwait },
#endif
#ifdef SYS_eventfd
    { "eventfd", SYS_eventfd },
#endif
#ifdef SYS_eventfd2
    { "eventfd2", SYS_eventfd2 },
#endif
#ifdef SYS_signalfd
    { "signalfd", SYS_signalfd },
#endif
#ifdef SYS_signalfd4
    { "signalfd4", SYS_signalfd4 },
#endif
#ifdef SYS_timerfd_create
    { "timerfd_create", SYS_timerfd_create },
#endif
#ifdef SYS_rt_sigaction
    { "rt_sigaction", SYS_rt_sigaction },
#endif
#ifdef SYS_rt_sigprocmask
    { "rt_sigprocmask", SYS_rt_sigprocmask },
#endif
#ifdef SYS_rt_sigreturn
    { "rt_sigreturn", SYS_rt_sigreturn },
#endif
#ifdef SYS_sigaltstack
    { "sigaltstack", SYS_sigaltstack },
#endif
#ifdef SYS_sched_yield
    { "sched_yield", SYS_sched_yield },
#endif
    { NULL, -1 } /* sentinel: keeps the initializer non-empty */
};
